

version: '3.1'

services:
  proxy:
    image: traefik:1.4
    command: --web --docker --docker.domain=localhost --logLevel=INFO
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    restart:
      always
  backdarksky:
    build:
      context: ../backdarksky
    ports:
      - "5000:5000"
    expose: [5000]
    networks:
      - webgateway
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.backend=backdarksky"
      - "traefik.frontend.redirect.regex=(*.)/api/(*.)"
      - "traefik.frontend.redirect.replacement=$$1:5000/$$2"
      - "traefik.frontend.rule=Host:locahost; PathPrefixStrip:/api"
      - "traefik.frontend.priority=49"
    restart:
      always
  frontdarksky:
    build: 
      context: ../frontdarksky
    expose: [3006]
    networks:
      - webgateway
    labels:
      - "traefik.enable=true"
      - "traefik.port=3006"
      - "traefik.backend=frontdarksky"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.frontend.priority=50"
    restart:
      always
networks:
  web:
    external:
      name: traefik_webgateway
  webgateway:
     driver: bridge

