version: '3.1'

services:
  proxy:
    image: traefik:1.4
    command: --web --docker --docker.domain=ec2-54-89-177-25.compute-1.amazonaws.com --logLevel=INFO
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    restart:
      always
  redis:
    image: redis:latest
    ports:
     - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    expose: [6379]
    restart: always
    networks:
      - webgateway
networks:
  web:
    external:
      name: traefik_webgateway
  webgateway:
     driver: bridge

